[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solidity_version = '0.8.22'
evm_version = 'shanghai'
fs_permissions = [{ access = "read-write", path = "./" }]
via_ir = false
exclude = [
    "lib/WAVS/**/*.sol",     # Exclude all Solidity files under lib/WAVS
    "lib/WAVS/lib/**/*.sol", # Explicitly exclude all Solidity files in WAVS lib subdirectories
]

remappings = [
    '@gnosis.pm/safe-contracts/=lib/safe-contracts/',
    '@gnosis.pm/conditional-tokens-contracts/=lib/conditional-tokens-contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@oz/=lib/openzeppelin-contracts/contracts',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@eigenlayer/contracts/=lib/WAVS/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/contracts/',
    '@eigenlayer/middleware/=lib/WAVS/lib/eigenlayer-middleware/',
    '@eigenlayer/test/=lib/WAVS/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/test/',
    'eigenlayer-contracts/=lib/WAVS/lib/eigenlayer-middleware/lib/eigenlayer-contracts/',
    'eigenlayer-middleware/=lib/WAVS/lib/eigenlayer-middleware/',
    '@gnosis.pm/zodiac/=lib/zodiac/',
    '@wavs=lib/WAVS/sdk/contracts/solidity/',
    '@layer-contracts=lib/WAVS/sdk/solidity/contracts/',
    '@eigenlayer-middleware=lib/WAVS/lib/eigenlayer-middleware/',
    '@eigenlayer-contracts=lib/WAVS/lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/contracts/',
    '@openzeppelin-upgrades/=lib/WAVS/lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/',
    '@openzeppelin-contracts/=lib/WAVS/lib/eigenlayer-middleware/lib/openzeppelin-contracts/contracts/',
    '@lay3rlabs/conditional-tokens-contracts/=lib/conditional-tokens-contracts/contracts/',
    '@lay3rlabs/conditional-tokens-market-makers/=lib/conditional-tokens-market-makers/contracts/',
]

[profile.bind]
keyword_prefix = "sol_"
module_root = "bindings"
binding_path = "bindings/bindings.rs"
rustfmt = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
